### ISSUE TITLE
Recipe filter seems to be broken

### ISSUE THREAD

**Issue by linusblom** [chas-academy/09-recipe-book-SebastianGerS#1]
Maybe I'm doing it wrong here, but I can't get filters on recipes to work. If I for example search for "Ice cream" and then check "Courses > Salads", desserts is still shown. Isn't that how it should work?

**Comment by SebastianGerS** [comment]
@linusblom Na it’s not suposed to be like that, allthougt you do have to select the filters before you type in your search. 
But i tested it again and there definetly seams to be a bug there.
But as far as I can tell the corect filters are being sent with the GET request, so i might be a problem with the yummly Api if theres not something that I not seeing (which is quit probable). 
But I will try to look some more att this during the weekend

**Comment by SebastianGerS** [comment]
To clerify my previus comment.
I have not actually added suport for filtering after the search has been made, but there seam to be some kind of problem even if one selects a filter before the search is made which might be related to a problem native to the api that i’m using

**Comment by SebastianGerS** [comment]
Ok so there was a problem with a value not beeing retrivable in production that coused the filters to not function at all. It’s now fixed and I also added func to enable filtering after a search had been made
